import type { Contact, Deal, Activity } from './types'

export const DEMO_CONTACTS: Contact[] = [
  { id:'dc1', name:'Carlos Torres', email:'c.torres@torres-asociados.es', phone:'+34 612 345 678', role:'CEO', type:'customer', owner:'LL', value:4500, location:'Barcelona', created_at:'2026-04-01T10:00:00Z', updated_at:'2026-05-28T10:00:00Z', user_id:'demo', company_id:'co1', company:{ id:'co1', name:'Torres & Asociados', industry:'Inmobiliaria', size:'12 empleados', website:'torres-asociados.es', created_at:'2026-04-01T10:00:00Z', user_id:'demo' } },
  { id:'dc2', name:'Ana Martínez', email:'a.martinez@clinicamartinez.es', phone:'+34 623 456 789', role:'Directora General', type:'prospect', owner:'ME', value:2800, location:'Madrid', created_at:'2026-04-15T10:00:00Z', updated_at:'2026-05-20T10:00:00Z', user_id:'demo', company_id:'co2', company:{ id:'co2', name:'Clínica Dental Martínez', industry:'Salud', size:'8 empleados', website:'clinicamartinez.es', created_at:'2026-04-15T10:00:00Z', user_id:'demo' } },
  { id:'dc3', name:'Javier Ruiz', email:'j.ruiz@logisticaiberica.com', phone:'+34 634 567 890', role:'COO', type:'prospect', owner:'TI', value:6200, location:'Valencia', created_at:'2026-03-20T10:00:00Z', updated_at:'2026-05-15T10:00:00Z', user_id:'demo', company_id:'co3', company:{ id:'co3', name:'Grupo Logístico Ibérica', industry:'Logística', size:'28 empleados', website:'logisticaiberica.com', created_at:'2026-03-20T10:00:00Z', user_id:'demo' } },
  { id:'dc4', name:'Sofía Vidal', email:'s.vidal@estudiovidal.es', phone:'+34 645 678 901', role:'Socia Fundadora', type:'lead', owner:'LL', value:1800, location:'Sevilla', created_at:'2026-05-05T10:00:00Z', updated_at:'2026-05-22T10:00:00Z', user_id:'demo', company_id:'co4', company:{ id:'co4', name:'Estudio Jurídico Vidal', industry:'Legal', size:'6 empleados', website:'estudiovidal.es', created_at:'2026-05-05T10:00:00Z', user_id:'demo' } },
  { id:'dc5', name:'Miguel Herrera', email:'m.herrera@dasur.es', phone:'+34 656 789 012', role:'Director de Operaciones', type:'customer', owner:'ME', value:3200, location:'Málaga', created_at:'2026-03-01T10:00:00Z', updated_at:'2026-05-05T10:00:00Z', user_id:'demo', company_id:'co5', company:{ id:'co5', name:'Distribuidora Alimentaria Sur', industry:'Alimentación', size:'19 empleados', website:'dasur.es', created_at:'2026-03-01T10:00:00Z', user_id:'demo' } },
]

export const DEMO_DEALS: Deal[] = [
  { id:'dd1', title:'Inspire Cyber 360 — Torres & Asociados', contact_id:'dc1', stage:'cliente_activo', value:4500, owner:'LL', precio_diagnostico:4500, precio_implementacion:12000, descuento_aplicado:0, ventas_status:'completado', marketing_status:'completado', operaciones_status:'en_progreso', delivery_status:'pendiente', created_at:'2026-04-01T10:00:00Z', updated_at:'2026-05-28T10:00:00Z', user_id:'demo', position:0, lead_source:'linkedin', responsable:'LL', contact:{ id:'dc1', name:'Carlos Torres', type:'customer', owner:'LL', value:4500, created_at:'', updated_at:'', user_id:'demo', company:{ id:'co1', name:'Torres & Asociados', created_at:'', user_id:'demo' } } },
  { id:'dd2', title:'Inspire Cyber 360 — Clínica Martínez', contact_id:'dc2', stage:'diagnostico_activo', value:2800, owner:'ME', precio_diagnostico:2800, precio_implementacion:8500, descuento_aplicado:0, ventas_status:'completado', marketing_status:'en_progreso', operaciones_status:'pendiente', delivery_status:'pendiente', created_at:'2026-04-15T10:00:00Z', updated_at:'2026-05-20T10:00:00Z', user_id:'demo', position:1, lead_source:'referido', responsable:'ME', contact:{ id:'dc2', name:'Ana Martínez', type:'prospect', owner:'ME', value:2800, created_at:'', updated_at:'', user_id:'demo', company:{ id:'co2', name:'Clínica Dental Martínez', created_at:'', user_id:'demo' } } },
  { id:'dd3', title:'Inspire Cyber 360 — Logística Ibérica', contact_id:'dc3', stage:'propuesta_implementacion', value:6200, owner:'TI', precio_diagnostico:6200, precio_implementacion:18000, descuento_aplicado:0, ventas_status:'completado', marketing_status:'completado', operaciones_status:'completado', delivery_status:'en_progreso', created_at:'2026-03-20T10:00:00Z', updated_at:'2026-05-15T10:00:00Z', user_id:'demo', position:2, lead_source:'web', responsable:'TI', contact:{ id:'dc3', name:'Javier Ruiz', type:'prospect', owner:'TI', value:6200, created_at:'', updated_at:'', user_id:'demo', company:{ id:'co3', name:'Grupo Logístico Ibérica', created_at:'', user_id:'demo' } } },
  { id:'dd4', title:'Inspire Cyber 360 — Estudio Vidal', contact_id:'dc4', stage:'reunion_inicial', value:1800, owner:'LL', precio_diagnostico:1800, precio_implementacion:5500, descuento_aplicado:0, ventas_status:'en_progreso', marketing_status:'pendiente', operaciones_status:'pendiente', delivery_status:'pendiente', created_at:'2026-05-05T10:00:00Z', updated_at:'2026-05-22T10:00:00Z', user_id:'demo', position:3, lead_source:'directo', responsable:'LL', contact:{ id:'dc4', name:'Sofía Vidal', type:'lead', owner:'LL', value:1800, created_at:'', updated_at:'', user_id:'demo', company:{ id:'co4', name:'Estudio Jurídico Vidal', created_at:'', user_id:'demo' } } },
  { id:'dd5', title:'Inspire Cyber 360 — Distribuidora Sur', contact_id:'dc5', stage:'cerrado', value:3200, owner:'ME', precio_diagnostico:3200, precio_implementacion:9800, descuento_aplicado:0, ventas_status:'completado', marketing_status:'completado', operaciones_status:'completado', delivery_status:'completado', created_at:'2026-03-01T10:00:00Z', updated_at:'2026-05-05T10:00:00Z', user_id:'demo', position:4, lead_source:'linkedin', responsable:'ME', notion_link:'https://notion.so/demo', fecha_entrega:'2026-06-01', contact:{ id:'dc5', name:'Miguel Herrera', type:'customer', owner:'ME', value:3200, created_at:'', updated_at:'', user_id:'demo', company:{ id:'co5', name:'Distribuidora Alimentaria Sur', created_at:'', user_id:'demo' } } },
]

export const DEMO_ACTIVITIES: Activity[] = [
  { id:'da1', type:'meeting', text:'Kickoff con Torres & Asociados. Accesos recibidos, empezamos cuestionarios esta semana.', owner:'LL', contact_id:'dc1', deal_id:'dd1', created_at: new Date(Date.now()-1*86400000).toISOString(), user_id:'demo', contact:DEMO_CONTACTS[0] },
  { id:'da2', type:'deal', text:'Deal Logística Ibérica avanzado a Propuesta de Implementación. Esperamos respuesta esta semana.', owner:'TI', contact_id:'dc3', deal_id:'dd3', created_at: new Date(Date.now()-3*86400000).toISOString(), user_id:'demo', contact:DEMO_CONTACTS[2] },
  { id:'da3', type:'email', text:'Propuesta enviada a Javier Ruiz con dos opciones de alcance (ops + ventas vs. completo).', owner:'TI', contact_id:'dc3', deal_id:'dd3', created_at: new Date(Date.now()-5*86400000).toISOString(), user_id:'demo', contact:DEMO_CONTACTS[2] },
  { id:'da4', type:'call', text:'Llamada con Ana Martínez. Dolor principal: gestión de citas y seguimiento post-visita.', owner:'ME', contact_id:'dc2', deal_id:'dd2', created_at: new Date(Date.now()-7*86400000).toISOString(), user_id:'demo', contact:DEMO_CONTACTS[1] },
  { id:'da5', type:'review', text:'Reunión de entrega con Distribuidora Sur. NPS: 10/10. Firmado upsell de implementación.', owner:'ME', contact_id:'dc5', deal_id:'dd5', created_at: new Date(Date.now()-9*86400000).toISOString(), user_id:'demo', contact:DEMO_CONTACTS[4] },
  { id:'da6', type:'note', text:'Sofía Vidal muy interesada en automatización de contratos. Enviar propuesta la próxima semana.', owner:'LL', contact_id:'dc4', deal_id:'dd4', created_at: new Date(Date.now()-11*86400000).toISOString(), user_id:'demo', contact:DEMO_CONTACTS[3] },
  { id:'da7', type:'demo', text:'Demo del CRM a medida con Carlos Torres. Muy positivo, quiere empezar implementación.', owner:'LL', contact_id:'dc1', deal_id:'dd1', created_at: new Date(Date.now()-14*86400000).toISOString(), user_id:'demo', contact:DEMO_CONTACTS[0] },
]
